spring:
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:media/,classpath:/static
  mvc:
    #
    static-path-pattern: /static/**

jwt:
  secret: jjjjjjjjjjjjjjjjjjjjjjjjjjjjjsssssssssssssssssssssssssssssshhhhhhhhhhhhhhhhhhhhhhhhhhhh
