name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_USER: ${{ secrets.MYSQL_ROOT_USER }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent"
